### ISSUE TITLE
Fix capitalisation

### ISSUE THREAD

**Issue by saethlin** [atvaccaro/slackbots#14]
Lowercase everything as it comes in and capitalise first word of response

**Comment by atvaccaro** [comment]
Is this done?

**Comment by saethlin** [comment]
Probably not. Since we're just building the Markov object once, I'm considering dictionary checking everything.

**Comment by saethlin** [comment]
Added something quick and dirty, but it seems to catch most things.

**Comment by saethlin** [comment]
Capitalize lone i

**Comment by saethlin** [comment]
Switch all capitalisation to regex and move to slack_importer.py, as it is now the biggest contributor to execution time on the first !markov call.
